services:
  grafana: # visualize metrics from thanos query
    build:
      context: ./services/metrics/grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GF_PORT}:${GF_PORT}"
    volumes:
      - ./services/metrics/grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./services/metrics/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./services/metrics/grafana/dashboards:${GF_DASHBOARDS_PATH}
    environment:
      - GF_LOG_LEVEL=error
      - GF_SERVER_HTTP_PORT=${GF_PORT}
      - GF_SERVER_PROTOCOL=https
      - GF_USERS_HOME_PAGE=/dashboards
      - GF_ROOT_URL=${GF_ADDR}
      - GF_DASHBOARDS_PATH=${GF_DASHBOARDS_PATH}
      - GF_URL_HEALTH=${GF_URL_HEALTH}
      - GF_ADDR=${GF_ADDR}
    networks:
      - vault
      - metrics
    labels:
    - "projectLabel=transcendence"

  minio: # long term storage for prometheus metrics (using thanos sidecar & thanos store)
    build:
      context: ./services/metrics/minio
      dockerfile: Dockerfile
    container_name: minio
    restart: unless-stopped
    expose:
      - "9000" # API S3
      - "9001" # UI
    volumes:
      - minio-data:/data
    environment:
      - MINIO_HEALTH_URL=${MINIO_HEALTH_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "${MINIO_HEALTH_URL}"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - vault
      - metrics_storage
    labels:
      - "projectLabel=transcendence"

  thanosSidecar: # upload prometheus metrics to minio + expose them to thanos query
    image: thanosio/thanos:v0.40.1
    container_name: thanosSidecar
    restart: unless-stopped
    user: "65534"
    volumes:
      - prometheus-data:/prometheus
      - ./services/metrics/thanosSidecar/thanos-storage.yml:/etc/thanos/storage.yml:ro
    command:
      - sidecar
      - --prometheus.url=http://prometheus:9090
      - --tsdb.path=/prometheus
      - --objstore.config-file=/etc/thanos/storage.yml
    depends_on:
      - prometheus
    networks:
      - metrics
      - metrics_storage
    labels:
      - "projectLabel=transcendence"

  thanosQuery: # send data from thanos sidecar (recent data) & thanos store (old data) to grafana
    image: thanosio/thanos:v0.40.1
    container_name: thanosQuery
    restart: unless-stopped
    expose:
      - ${THANOS_QUERY_PORT}
    command:
      - query
      - "--http-address=0.0.0.0:${THANOS_QUERY_PORT}"
      - "--endpoint=thanosSidecar:${THANOS_PORT}"
      - "--endpoint=thanosStore:${THANOS_PORT}"
    depends_on:
      - thanosSidecar
      - thanosStore
    networks:
      - metrics
      - metrics_storage
    labels:
      - "projectLabel=transcendence"

  thanosStore: # read data from minio + provide them to thanos query with thanos sidecar
    image: thanosio/thanos:v0.40.1
    container_name: thanosStore
    restart: unless-stopped
    volumes:
      - thanos-store-data:/data
      - ./services/metrics/thanosSidecar/thanos-storage.yml:/etc/thanos/storage.yml:ro
    user: "1001:1001"
    command:
      - store
      - "--data-dir=/data"
      - "--objstore.config-file=/etc/thanos/storage.yml"
    networks:
      - metrics_storage
    labels:
      - "projectLabel=transcendence"

  prometheus: # scrape metrics and store them for short-term storage + provide them to thanos sidecar
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    restart: unless-stopped
    expose:
      - ${PROMETHEUS_PORT}
    user: "65534"
    volumes:
      - ./services/metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./services/metrics/prometheus/rules:/etc/prometheus/rules
      - prometheus-data:/prometheus
    environment:
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.min-block-duration=2m" # for testing purpose, default is 2h
      - "--storage.tsdb.max-block-duration=2m" # for testing purpose, default is 24h
      - "--storage.tsdb.retention.time=2m" # for testing purpose, default is 15d
      # prometheus will receive cadvisor metrics that are too old because of these
    networks:
      - transcendence
      - metrics
    labels:
      - "projectLabel=transcendence"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - ${CADVISOR_PORT}
    volumes:
      - /:/rootsfs:ro # see filesys of host -> mesure host disk usage
      - /var/run:/var/run:ro # docker socket + containers info -> list containers running
      - /sys:/sys:ro # system info -> hardware stats (cpu, mem, io usage)
      - /var/lib/docker/:/var/lib/docker:ro # docker metadata (images, containers, volumes...) -> container stats
    networks:
      - metrics
    labels:
    - "projectLabel=transcendence"

  node_exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - ${NODE_EXPORTER_PORT}
    pid: "host" # pour avoir les bonnes stats cpu/mem/io du host
    volumes:
      - /proc:/host/proc:ro # host process info -> cpu, mem, io stats
      - /sys:/host/sys:ro # host system info -> hardware stats (cpu, mem, io usage)
      - /:/rootfs:ro # host filesystem info -> disk usage stats
    networks:
      - metrics
    labels:
      - "projectLabel=transcendence"

  docker_custom_exporter:
    build:
      context: ./services/metrics/docker_custom_exporter
      dockerfile: Dockerfile
    container_name: docker_custom_exporter
    restart: unless-stopped
    expose:
      - ${DOCKER_CUSTOM_EXPORTER_PORT}
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH} # pour communiquer avec le daemon docker
    environment:
      - DOCKER_CUSTOM_EXPORTER_PORT=${DOCKER_CUSTOM_EXPORTER_PORT}
      - SOCKET_PATH=${SOCKET_PATH}
    networks:
      - metrics
    labels:
    - "projectLabel=transcendence"

  alertmanager:
    image: prom/alertmanager:v0.29.0
    container_name: alert_manager
    restart: unless-stopped
    expose:
      - ${ALERTMANAGER_PORT}
    volumes:
      - ./services/metrics/alertManager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - metrics
    labels:
      - "projectLabel=transcendence"

volumes:
  minio-data:
  thanos-store-data:
  prometheus-data:

networks:
  transcendence:
    name: transcendence_network
    driver: bridge
  vault:
    name: vault_network
    driver: bridge
    external: true
  metrics:
    name: metrics_network
    driver: bridge
  metrics_storage:
    name: metrics_storage_network
    driver: bridge