services:
  grafana:
    build:
      context: ./services/metrics/grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: unless-stopped
    user: '0' # root, otherwisse find right id with cmd 'id -u'
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - ./services/metrics/grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./services/metrics/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./services/metrics/grafana/dashboards:${GRAFANA_DASHBOARDS_PATH}
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
      - GF_SERVER_PROTOCOL=https
      - GF_ROOT_URL=https://localhost:${GRAFANA_PORT}
      - GF_SERVER_CERT_FILE=${GRAFANA_CERT_PATH}
      - GF_SERVER_CERT_KEY=${GRAFANA_KEY_PATH}
      - GRAFANA_DASHBOARDS_PATH=${GRAFANA_DASHBOARDS_PATH}
    networks:
      - metrics
    labels:
    - "projectLabel=transcendence"

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    restart: unless-stopped
    expose:
      - ${PROMETHEUS_PORT}
    volumes:
      - ./services/metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./services/metrics/prometheus/rules:/etc/prometheus/rules
      - prometheus-data:/prometheus
    environment:
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    networks:
      - transcendence
      - metrics
    labels:
      - "projectLabel=transcendence"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - ${CADVISOR_PORT}
    volumes:
      - /:/rootsfs:ro # see filesys of host -> mesure host disk usage
      - /var/run:/var/run:ro # docker socket + containers info -> list containers running
      - /sys:/sys:ro # system info -> hardware stats (cpu, mem, io usage)
      - /var/lib/docker/:/var/lib/docker:ro # docker metadata (images, containers, volumes...) -> container stats
    networks:
      - metrics
    labels:
    - "projectLabel=transcendence"

  node_exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - ${NODE_EXPORTER_PORT}
    pid: "host" # pour avoir les bonnes stats cpu/mem/io du host
    volumes:
      - /proc:/host/proc:ro # host process info -> cpu, mem, io stats
      - /sys:/host/sys:ro # host system info -> hardware stats (cpu, mem, io usage)
      - /:/rootfs:ro # host filesystem info -> disk usage stats
    networks:
      - metrics
    labels:
      - "projectLabel=transcendence"

  docker_custom_exporter:
    build:
      context: ./services/metrics/docker_custom_exporter
      dockerfile: Dockerfile
    container_name: docker_custom_exporter
    restart: unless-stopped
    expose:
      - ${DOCKER_CUSTOM_EXPORTER_PORT}
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH} # pour communiquer avec le daemon docker
    environment:
      - DOCKER_CUSTOM_EXPORTER_PORT=${DOCKER_CUSTOM_EXPORTER_PORT}
      - SOCKET_PATH=${SOCKET_PATH}
    networks:
      - metrics
    labels:
    - "projectLabel=transcendence"

  alertmanager:
    image: prom/alertmanager:v0.29.0
    container_name: alert_manager
    restart: unless-stopped
    expose:
      - ${ALERTMANAGER_PORT}
    volumes:
      - ./services/metrics/alertManager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - ALERT_HOST=${ALERT_HOST}
      - ALERT_FROM=${ALERT_FROM}
      - ALERT_AUTH_USER=${ALERT_AUTH_USER}
      - ALERT_AUTH_PWD=${ALERT_AUTH_PWD}
      - ALERT_TO=${ALERT_TO}
    networks:
      - metrics
    labels:
      - "projectLabel=transcendence"

volumes:
  prometheus-data:

networks:
  transcendence:
    name: transcendence_network
    driver: bridge
  metrics:
    name: metrics_network
    driver: bridge
