services:
  grafana:
    build:
      context: ./services/grafana
      dockerfile: Dockerfile
    container_name: grafana
    user: '0' # root, otherwisse find right id with cmd 'id -u'
    ports:
      - "4000:4000"
    environment:
      - GF_SERVER_HTTP_PORT=4000 # user = admin, pwd = admin
      # - GF_SECURITY_ADMIN_PASSWORD=your_password
    volumes:
      - ./services/grafana/provisioning:/etc/grafana/provisioning
      - ./services/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./services/prometheus/rules:/etc/prometheus/rules
    networks:
      - transcendence
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootsfs:ro # see filesys of host -> mesure host disk usage
      - /var/run:/var/run:ro # docker socket + containers info -> list containers running
      - /sys:/sys:ro # system info -> hardware stats (cpu, mem, io usage)
      - /var/lib/docker/:/var/lib/docker:ro # docker metadata (images, containers, volumes...) -> container stats
    networks:
      - monitoring
  
  node_exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter
    ports:
      - "9100:9100"
    pid: "host" # pour avoir les bonnes stats cpu/mem/io du host
    volumes:
      - /proc:/host/proc:ro # host process info -> cpu, mem, io stats
      - /sys:/host/sys:ro # host system info -> hardware stats (cpu, mem, io usage)
      - /:/rootfs:ro # host filesystem info -> disk usage stats
    networks:
      - monitoring

  docker_custom_exporter:
    build:
      context: ./services/docker_custom_exporter
      dockerfile: Dockerfile
    container_name: docker_custom_exporter
    ports:
      - "6789:6789"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # pour communiquer avec le daemon docker
    networks:
      - monitoring
  
  alertmanager:
    image: prom/alertmanager:v0.29.0
    container_name: alert_manager
    ports:
      - "9093:9093"
    volumes:
      - ./services/alertManager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

networks:
  transcendence:
    name: transcendence_network
    driver: bridge
  monitoring:
    name: monitoring_network
    driver: bridge
  elk:
    name: elk_network
    driver: bridge
